name: My First Workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Multiple-commands-execution
        run: |
             echo "My first GitHub Actions Job"
             ls -ltra
             cat README.md

      -   name: ASCII generator 
          run: cowsay -f dragon "Run for cover.... I am a dragon ">> dragon.txt 

      # - name: List files
      # run: ls

      #- name: Read File
      # run: cat README.md