name: Testing Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: [srivas-VirtualBox]
    steps:
      - name: Echo content
        run: |
          echo "ok"
          sleep 15s
